spring.application.name=nurigo

spring.datasource.url=jdbc:postgresql://localhost:5433/temp_project
spring.datasource.username=temp_user
spring.datasource.password=temp_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

server.port=8080