CREATE TABLE public.markets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    boundary geometry (Polygon, 4326) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    name varchar(100) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);

CREATE INDEX idx_markets_boundary_gist ON public.markets USING gist (boundary);

CREATE TABLE public.stores (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_name varchar(100),
    created_at timestamp(6) without time zone NOT NULL,
    location geometry (Point, 4326) NOT NULL,
    major_category_code varchar(10) NOT NULL,
    major_category_name varchar(50) NOT NULL,
    middle_category_code varchar(10),
    middle_category_name varchar(100),
    name varchar(200) NOT NULL,
    road_address varchar(300),
    small_category_code varchar(10),
    small_category_name varchar(100),
    source_id varchar(32) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT uk_stores_source_id UNIQUE (source_id)
);

CREATE INDEX idx_stores_location_gist ON public.stores USING gist (location);

CREATE TABLE public.mission_definitions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activation_reason varchar(500) NOT NULL,
    active boolean NOT NULL,
    capacity integer,
    category varchar(30) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description varchar(500) NOT NULL,
    display_order integer NOT NULL,
    mission_group varchar(20) NOT NULL,
    mission_key varchar(100) NOT NULL,
    progress_target integer NOT NULL,
    reward_points integer NOT NULL,
    target_address varchar(300),
    target_id bigint NOT NULL,
    target_latitude double precision NOT NULL,
    target_longitude double precision NOT NULL,
    target_name varchar(200) NOT NULL,
    target_type varchar(20) NOT NULL,
    title varchar(200) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    verification_label varchar(300) NOT NULL,
    CONSTRAINT uk_mission_definitions_mission_key UNIQUE (mission_key),
    CONSTRAINT mission_definitions_category_check CHECK (
        category IN (
            'VISIT',
            'EXPLORATION',
            'CHALLENGE',
            'OTHER'
        )
    ),
    CONSTRAINT mission_definitions_mission_group_check CHECK (
        mission_group IN ('DAILY', 'SPECIAL')
    ),
    CONSTRAINT mission_definitions_target_type_check CHECK (
        target_type IN ('MARKET', 'STORE')
    )
);

CREATE TABLE public.daily_mission_assignments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assignment_date date NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    progress_current integer NOT NULL,
    status varchar(30) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    user_id varchar(100) NOT NULL,
    version bigint NOT NULL,
    mission_definition_id bigint NOT NULL,
    CONSTRAINT daily_mission_assignments_status_check CHECK (
        status IN (
            'AVAILABLE',
            'IN_PROGRESS',
            'COMPLETED',
            'CLAIMED',
            'CLOSED'
        )
    ),
    CONSTRAINT uk_daily_mission_user_date_definition UNIQUE (
        user_id,
        assignment_date,
        mission_definition_id
    ),
    CONSTRAINT fk_daily_mission_assignment_definition FOREIGN KEY (mission_definition_id) REFERENCES public.mission_definitions (id)
);